[package]
name = "rustcast"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Raycast for Linux"
readme = "README.md"

[dependencies]
gtk = { version = "0.9.2", package = "gtk4", features = ["v4_12"] }

[dev-dependencies]
cargo-watch = "8.4"
