# https://numtide.github.io/devshell
imports = [
  "language.rust",
  "git.hooks"
]

[git]
hooks.enable = true
hooks.pre-commit.text = "rustfmt"

[devshell]
name = "rustcast"

packages = [
  "gtk4",
  "pkg-config",
  "nixpkgs-fmt",
]

packagesFrom = [
  "direnv"
]

[[commands]]
package = "nixpkgs-fmt"
category = "formatters"

[[commands]]
name = "tests"
command = "cargo test"
help = "Run cargo tests"
category = "rust"

[[commands]]
name = "clippy"
command = "cargo clippy"
help = "Run cargo clippy"
category = "rust"

[[commands]]
name = "clean"
command = "cargo clean"
help = "Run cargo clean"
category = "rust"
